/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Produto;
import Interfaces.CadastrarSabor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ModelProdutos;
import util.TeclasPermitidasDecimais;

/**
 *
 * @author Paladino
 */
public class BuscarProdutoPrincipal extends javax.swing.JInternalFrame {

    Produto prod = new Produto();
    ModelProdutos modeloProduto = new ModelProdutos();

    /**
     * Creates new form BuscarProduto
     */
    public BuscarProdutoPrincipal() {
        initComponents();
        jTableProduto.setModel(modeloProduto);

        jtxBuscaValor.setDocument(new TeclasPermitidasDecimais());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtxBuscaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtxBuscaDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbtAlimenticio = new javax.swing.JRadioButton();
        rbtPapelaria = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxBuscaValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbSabor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Produto");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        jtxBuscaNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jTableProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        jtxBuscaDescricao.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Categoria");

        buttonGroup1.add(rbtAlimenticio);
        rbtAlimenticio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbtAlimenticio.setText("Alimentício");
        rbtAlimenticio.setEnabled(false);

        buttonGroup1.add(rbtPapelaria);
        rbtPapelaria.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbtPapelaria.setText("Papelaria");
        rbtPapelaria.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Valor Unitario");

        jtxBuscaValor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Sabor");

        cbSabor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --" }));
        cbSabor.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtAlimenticio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtPapelaria))
                    .addComponent(jtxBuscaDescricao)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtxBuscaValor)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(cbSabor, 0, 231, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAlimenticio)
                    .addComponent(rbtPapelaria))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxBuscaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxBuscaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setText("Salvar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        modeloProduto.removeAllRows();

        ResultSet rs = null;
        Conexao con = new Conexao();
        con.getConexao();

        List<Produto> ListProduto = new ArrayList<>();

        try {

            String sqlBuscaProduto = "select *from dados.produto where nome ~*?;";
            String sqlBuscarSabor = "select nome_sabor from dados.sabor where id_sabor = ?";
            PreparedStatement stmBuscarSabor = con.getConexao().prepareStatement(sqlBuscarSabor);
            PreparedStatement stmBuscaProduto = con.getConexao().prepareStatement(sqlBuscaProduto);
            stmBuscaProduto.setString(1, jtxBuscaNome.getText());
            rs = stmBuscaProduto.executeQuery();
            ResultSet rsSabor = null;

            if (rs.next()) {

                do {
                    stmBuscarSabor.setInt(1, rs.getInt("sabor"));
                    rsSabor = stmBuscarSabor.executeQuery();
                    rsSabor.next();
                    Produto produto = new Produto();
                    produto.setSabor(rsSabor.getString("nome_sabor"));
                    produto.setNome(rs.getString("nome"));
                    produto.setDescricao(rs.getString("descricao"));
                    produto.setValor(rs.getFloat("valor"));
                    produto.setCategoria(rs.getString("categoria"));
                    ListProduto.add(produto);

                } while (rs.next());

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            con.fecharConexao();
        }

        for (Produto p : ListProduto) {
            modeloProduto.addRow(p);
        }

        carregarcb();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked

        int linha = jTableProduto.getSelectedRow();

        if (linha >= 0) {

            jtxBuscaNome.setText((String) jTableProduto.getValueAt(linha, 0));
            jtxBuscaDescricao.setText((String) jTableProduto.getValueAt(linha, 1));
            jtxBuscaValor.setText(String.valueOf(jTableProduto.getValueAt(linha, 2)));

            if (jTableProduto.getValueAt(linha, 3).equals("Alimentício")) {
                rbtAlimenticio.setSelected(true);
            } else {
                rbtPapelaria.setSelected(true);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProdutoMouseClicked

    public void carregarcb() {

        Conexao buscar = new Conexao();
        buscar.getConexao();
        String buscarSabor = "SELECT nome_sabor FROM dados.sabor order by nome_sabor;";
        @SuppressWarnings("UnusedAssignment")
        ResultSet rs = null;
        try {
            PreparedStatement smtBuscarSabor = buscar.getConexao().prepareStatement(buscarSabor);
            rs = smtBuscarSabor.executeQuery();
            while (rs.next()) {
                cbSabor.addItem(rs.getString("nome_sabor"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(CadastrarSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Principal.usuario.getNivel() == 2){
            JOptionPane.showMessageDialog(null, "Ação permitida somente para Administradores", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Conexao con = new Conexao();
        con.getConexao();
        ResultSet rs = null;

        String categoria = "";

        prod.setNome(jtxBuscaNome.getText());
        prod.setDescricao(jtxBuscaDescricao.getText());
        prod.setValor(Float.parseFloat(jtxBuscaValor.getText()));
        prod.setSabor(String.valueOf(cbSabor.getSelectedItem()));

        if (rbtAlimenticio.isSelected()) {
            categoria = "Alimentício";
            prod.setCategoria(categoria);
        } else {
            categoria = "Papelaria";
            prod.setCategoria(categoria);
        }

        try {

            String sabor = prod.getSabor();

            String sqlAlteraProduto = "UPDATE dados.produto SET nome=?, descricao=?, valor=?, categoria=?, sabor=? WHERE nome = '" + jtxBuscaNome.getText() + "';";

            String buscarSabor = "select id_sabor from dados.sabor where nome_sabor = '" + sabor + "';";
            PreparedStatement stmBuscaSabor = con.getConexao().prepareStatement(buscarSabor);
            rs = stmBuscaSabor.executeQuery();
            rs.next();

            int cod = rs.getInt("id_sabor");

            PreparedStatement stmAlteraProduto = con.getConexao().prepareStatement(sqlAlteraProduto);
            stmAlteraProduto.setString(1, prod.getNome());
            stmAlteraProduto.setString(2, prod.getDescricao());
            stmAlteraProduto.setFloat(3, prod.getValor());
            stmAlteraProduto.setString(4, prod.getCategoria());
            stmAlteraProduto.setInt(5, cod);
            stmAlteraProduto.executeUpdate();

            JOptionPane.showMessageDialog(null, "Produto Alterado com sucesso!");

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e);
        } finally {
            con.fecharConexao();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed

            if(Principal.usuario.getNivel() == 2){
                JOptionPane.showMessageDialog(null, "Opção Permitida somente para Administradores", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            cbSabor.setEnabled(true);
            jtxBuscaDescricao.setEnabled(true);
            jtxBuscaValor.setEnabled(true);
            rbtAlimenticio.setEnabled(true);
            rbtPapelaria.setEnabled(true);

       

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jtxBuscaDescricao.setText("");
        jtxBuscaValor.setText("");
        modeloProduto.removeAllRows();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSabor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JTextField jtxBuscaDescricao;
    private javax.swing.JTextField jtxBuscaNome;
    private javax.swing.JTextField jtxBuscaValor;
    private javax.swing.JRadioButton rbtAlimenticio;
    private javax.swing.JRadioButton rbtPapelaria;
    // End of variables declaration//GEN-END:variables
}
