/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Produto;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.TabelaBuscarProduto;

/**
 *
 * @author joao
 */
public class BuscarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProduto
     */
    TabelaBuscarProduto tableModel = new TabelaBuscarProduto();
    List<Produto> produtos = new ArrayList<>();
    private String tela;
    public BuscarProduto(String tela) {
        initComponents();
        jTable1.setModel(tableModel);
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Produto:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Selecionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite Algum Produto", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtNome.requestFocus();
            return;

        }
        tableModel.removeAllRow();
        String buscarProdutos = "SELECT codigo_produto, nome, descricao, valor, categoria, sabor FROM dados.produto WHERE nome ~* ?";
        String buscarSabor = "SELECT nome_sabor FROM dados.sabor WHERE id_sabor = ?";
        ResultSet rsProdutos = null;
        ResultSet rsSabor = null;
        Conexao minhaConexao = new Conexao();
        try {
            PreparedStatement stmBuscarProdutos = minhaConexao.getConexao().prepareStatement(buscarProdutos);
            stmBuscarProdutos.setString(1, jtNome.getText());
            rsProdutos = stmBuscarProdutos.executeQuery();
            if(rsProdutos.next()){
                do{
                    Produto novo = new Produto();
                    novo.setCategoria(rsProdutos.getString("categoria"));
                    novo.setCodigo_produto(rsProdutos.getInt("codigo_produto"));
                    novo.setDescricao(rsProdutos.getString("descricao"));
                    novo.setNome(rsProdutos.getString("nome"));
                    PreparedStatement stmBuscarSabor = minhaConexao.getConexao().prepareStatement(buscarSabor);
                    stmBuscarSabor.setInt(1, rsProdutos.getInt("sabor"));
                    rsSabor = stmBuscarSabor.executeQuery();
                    rsSabor.next();
                    novo.setSabor(rsSabor.getString("nome_sabor"));
                    novo.setValor(rsProdutos.getFloat("valor"));
                    produtos.add(novo);
                    
                }while(rsProdutos.next());
            }else{
                JOptionPane.showMessageDialog(null, "Produto não Cadastrado", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(BuscarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Produto p : produtos){
            tableModel.addRow(p);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTable1.getSelectedRow() >= 0){
            if(tela.equals("Cadastrar Pedido")){
                 CadastrarPedido.cbproduto.setSelectedItem(produtos.get(jTable1.getSelectedRow()).getNome());
                this.dispose();
            }else{
                AlterarPedido.cbProduto.setSelectedItem(produtos.get(jTable1.getSelectedRow()).getNome());
                this.dispose();
            }
            
           
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Produto", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}
