/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Cliente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ModelCliente;
import util.TeclasPermitidasLetras;
import util.TeclasPermitidasNumeros;

/**
 *
 * @author Paladino
 */
public class BuscarClientePrincipal extends javax.swing.JInternalFrame {

    String jtxBuscaClienteAux;
    String jtxBuscaCodigoAux;

    ModelCliente modeloCliente = new ModelCliente();

    /**
     * Creates new form BuscarCliente
     */
    public BuscarClientePrincipal() {
        initComponents();
        jtxNome.setEnabled(false);
        jtxBuscarTelefone.setEnabled(false);
        jTableCliente.setModel(modeloCliente);
        jtxBuscaNumero.setDocument(new TeclasPermitidasNumeros());
        jtxBuscaCidade.setDocument(new TeclasPermitidasLetras());
        jtxBuscaNome.setDocument(new TeclasPermitidasLetras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxBuscaRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxBuscaBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxBuscaComplemento = new javax.swing.JTextField();
        jtxBuscaCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxBuscaNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxBuscarTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jbtEditar = new javax.swing.JButton();
        jtbSalvar = new javax.swing.JButton();
        jtbBuscar = new javax.swing.JButton();
        jtxBuscaNome = new javax.swing.JTextField();
        jlnome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Busca Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Localização", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Rua");

        jtxBuscaRua.setEnabled(false);
        jtxBuscaRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxBuscaRuaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Bairro");

        jtxBuscaBairro.setEnabled(false);
        jtxBuscaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxBuscaBairroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Complemento");

        jtxBuscaComplemento.setEnabled(false);

        jtxBuscaCidade.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Cidade");

        jtxBuscaNumero.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Número");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Telefone");

        try {
            jtxBuscarTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        jtxNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxBuscaRua, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxBuscarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jtxNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 410, Short.MAX_VALUE))
                            .addComponent(jtxBuscaBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxBuscaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtxBuscaComplemento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxBuscaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxBuscaRua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxBuscarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxBuscaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxBuscaComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtxBuscarTelefone.getAccessibleContext().setAccessibleName("");

        jbtEditar.setBackground(new java.awt.Color(204, 204, 204));
        jbtEditar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.setToolTipText("");
        jbtEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        jtbSalvar.setBackground(new java.awt.Color(204, 204, 204));
        jtbSalvar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jtbSalvar.setText("Salvar");
        jtbSalvar.setToolTipText("");
        jtbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbSalvar.setEnabled(false);
        jtbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbSalvarActionPerformed(evt);
            }
        });

        jtbBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jtbBuscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jtbBuscar.setText("Buscar");
        jtbBuscar.setToolTipText("");
        jtbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbBuscarActionPerformed(evt);
            }
        });

        jtxBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxBuscaNomeActionPerformed(evt);
            }
        });

        jlnome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlnome.setText("Nome");

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jtbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(383, 383, 383))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jlnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1120, 595);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxBuscaRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxBuscaRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxBuscaRuaActionPerformed

    private void jtxBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxBuscaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxBuscaNomeActionPerformed

    private void jtxBuscaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxBuscaBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxBuscaBairroActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed

        jtxBuscaNome.setEnabled(true);
        jtxBuscarTelefone.setEnabled(true);
        jtxBuscaRua.setEnabled(true);
        jtxBuscaBairro.setEnabled(true);
        jtxBuscaComplemento.setEnabled(true);
        jtxBuscaCidade.setEnabled(true);
        jtxBuscaNumero.setEnabled(true);
        jtbSalvar.setEnabled(true);
        jtxNome.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jtbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbBuscarActionPerformed

        modeloCliente.removeAllRows();

        ResultSet rs = null;
        @SuppressWarnings("UnusedAssignment")
        ResultSet rse = null;
        Conexao con = new Conexao();
        con.getConexao();

        List<Cliente> clientes = new ArrayList<>();

        try {

            String sqlCliente = "SELECT *from dados.cliente where nome ~*?;";
            PreparedStatement stmBuscaCliente = con.getConexao().prepareStatement(sqlCliente);
            stmBuscaCliente.setString(1, jtxBuscaNome.getText());
            rse = stmBuscaCliente.executeQuery();

            if (rse.next()) {
                do {

                    Cliente cliente = new Cliente();

                    cliente.setNome(rse.getString("nome"));
                    cliente.setTelefone(rse.getString("telefone"));
                    cliente.setRua(rse.getString("rua"));
                    cliente.setBairro(rse.getString("bairro"));
                    cliente.setNumero(rse.getInt("numero"));
                    cliente.setComplemento(rse.getString("complemento"));
                    cliente.setCidade(rse.getString("cidade"));
                    
                    clientes.add(cliente);

                } while (rse.next());

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            con.fecharConexao();
        }

        for (Cliente c : clientes) {
            modeloCliente.addRows(c);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jtbBuscarActionPerformed

    private void jtbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbSalvarActionPerformed

        Cliente cliente = new Cliente();

        if (jtxNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo NOME não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxNome.requestFocus();
        } else if (jtxBuscaRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo RUA não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscaRua.requestFocus();
        } else if (jtxBuscarTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo TELEFONE não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscarTelefone.requestFocus();
        } else if (jtxBuscaBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo BAIRRO não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscaBairro.requestFocus();
        } else if (jtxBuscaCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo CIDADE não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscaCidade.requestFocus();
        } else if (jtxBuscaComplemento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo COMPLEMENTO não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscaComplemento.requestFocus();
        } else if (jtxBuscaNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo NUMERO não pode ser vazio!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxBuscaNumero.requestFocus();
        } else {
            cliente.setNome(jtxNome.getText());
            cliente.setRua(jtxBuscaRua.getText());
            cliente.setTelefone(jtxBuscarTelefone.getText());
            cliente.setBairro(jtxBuscaBairro.getText());
            cliente.setCidade(jtxBuscaCidade.getText());
            cliente.setComplemento(jtxBuscaComplemento.getText());
            cliente.setNumero(Integer.parseInt(jtxBuscaNumero.getText()));

            Conexao con = new Conexao();
            con.getConexao();
            ResultSet rs = null;

            try {

                String sqlCod = "Select codigo_cliente from dados.cliente where nome = '" + jtxBuscaNome.getText() + "';";
                PreparedStatement stmBuscaCod = con.getConexao().prepareStatement(sqlCod);
                rs = stmBuscaCod.executeQuery();
                rs.next();

                int cod = rs.getInt("codigo_cliente");

                String sql = "UPDATE dados.cliente SET nome=?, telefone=?, rua=?, bairro=?, cidade=?, numero=?, complemento=? WHERE cliente.codigo_cliente = '" + cod + "';";

                PreparedStatement stmAlteraCliente = con.getConexao().prepareStatement(sql);
                stmAlteraCliente.setString(1, cliente.getNome());
                stmAlteraCliente.setString(2, cliente.getTelefone());
                stmAlteraCliente.setString(3, cliente.getRua());
                stmAlteraCliente.setString(4, cliente.getBairro());
                stmAlteraCliente.setString(5, cliente.getCidade());
                stmAlteraCliente.setInt(6, cliente.getNumero());
                stmAlteraCliente.setString(7, cliente.getComplemento());
                stmAlteraCliente.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cliente Salvo com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                con.fecharConexao();
            }

        }
        
        jtxBuscaNome.setText("");
        jtxNome.setText("");
        jtxBuscaBairro.setText("");
        jtxBuscaComplemento.setText("");
        jtxBuscaCidade.setText("");
        jtxBuscaRua.setText("");
        jtxBuscaNumero.setText("");
        jtxBuscarTelefone.setText("");
        modeloCliente.removeAllRows();
        
    }//GEN-LAST:event_jtbSalvarActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked

        int linha = jTableCliente.getSelectedRow();

        if (linha != -1) {

            jtxBuscaNome.setText((String) jTableCliente.getValueAt(linha, 0));
            jtxNome.setText((String)jTableCliente.getValueAt(linha, 0));
            jtxBuscarTelefone.setText((String) jTableCliente.getValueAt(linha, 1));
            jtxBuscaRua.setText((String) jTableCliente.getValueAt(linha, 2));
            jtxBuscaBairro.setText((String) jTableCliente.getValueAt(linha, 3));
            jtxBuscaNumero.setText(String.valueOf(jTableCliente.getValueAt(linha, 4)));
            jtxBuscaComplemento.setText((String) jTableCliente.getValueAt(linha, 5));
            jtxBuscaCidade.setText((String) jTableCliente.getValueAt(linha, 6));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jtxNome.setText("");
        jtxBuscaCidade.setText("");
        jtxBuscaBairro.setText("");
        jtxBuscaNumero.setText("");
        jtxBuscarTelefone.setText("");
        jtxBuscaRua.setText("");
        jtxBuscaComplemento.setText("");
        modeloCliente.removeAllRows();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JLabel jlnome;
    private javax.swing.JButton jtbBuscar;
    private javax.swing.JButton jtbSalvar;
    private javax.swing.JTextField jtxBuscaBairro;
    private javax.swing.JTextField jtxBuscaCidade;
    private javax.swing.JTextField jtxBuscaComplemento;
    private javax.swing.JTextField jtxBuscaNome;
    private javax.swing.JTextField jtxBuscaNumero;
    private javax.swing.JTextField jtxBuscaRua;
    private javax.swing.JFormattedTextField jtxBuscarTelefone;
    private javax.swing.JTextField jtxNome;
    // End of variables declaration//GEN-END:variables
}
