/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Produto;
import static Interfaces.Principal.jDesktopPane1;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastrarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
        carregarcb();
        cbsabor.setEnabled(false);
        jButton4.setEnabled(false);
        Principal.verificarProduto = false;
    }
   
    public static void carregarcb(){
    
     Conexao buscar = new Conexao();
        buscar.getConexao();
        String buscarSabor = "SELECT nome_sabor FROM dados.sabor order by nome_sabor;";
        @SuppressWarnings("UnusedAssignment")
        ResultSet rs = null;
        try{
            PreparedStatement smtBuscarSabor = buscar.getConexao().prepareStatement(buscarSabor);
            rs = smtBuscarSabor.executeQuery();
            if(rs.next()){
                do{
                    cbsabor.addItem(rs.getString("nome_sabor"));
                }while(rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlvalor = new javax.swing.JLabel();
        jtvalor = new javax.swing.JTextField();
        jlsabor = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        jtnome = new javax.swing.JTextField();
        jldescricao = new javax.swing.JLabel();
        jtdescricao = new javax.swing.JTextField();
        cbsabor = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jralimento = new javax.swing.JRadioButton();
        jrpapelaria = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Produto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        jlvalor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlvalor.setText("Valor Unitario:");

        jtvalor.setToolTipText("Obrigatorio");

        jlsabor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlsabor.setText("Sabor:");

        jlnome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlnome.setText("Nome:");

        jtnome.setToolTipText("Obrigatorio");

        jldescricao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jldescricao.setText("Descrição:");

        jtdescricao.setToolTipText("Opcional");

        cbsabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--" }));
        cbsabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsaborActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mais.jpg"))); // NOI18N
        jButton4.setToolTipText("Adicionar Sabor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jldescricao)
                    .addComponent(jlnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtnome)
                    .addComponent(jtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlsabor)
                    .addComponent(jlvalor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbsabor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnome)
                    .addComponent(jtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlvalor)
                    .addComponent(jtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jldescricao)
                        .addComponent(jtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbsabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlsabor)))
                .addGap(50, 50, 50))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ação"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Sair");
        jButton3.setToolTipText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.setToolTipText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.setToolTipText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Categoria:");

        buttonGroup1.add(jralimento);
        jralimento.setText("Alimentício");
        jralimento.setToolTipText("Alimentício");
        jralimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jralimentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrpapelaria);
        jrpapelaria.setText("Papelaria");
        jrpapelaria.setToolTipText("Papelaria");
        jrpapelaria.setActionCommand(getToolTipText());
        jrpapelaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrpapelariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jralimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrpapelaria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jralimento)
                    .addComponent(jrpapelaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtdescricao.setText("");
        jtnome.setText("");
        cbsabor.setSelectedIndex(0);
        jtvalor.setText("");
        buttonGroup1.clearSelection();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo nome nao pode ser Vazio", "ERROR", JOptionPane.ERROR_MESSAGE);
            jtnome.requestFocus();
            return;
        }
        if (jtvalor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Valor nao pode ser Vazio", "ERROR", JOptionPane.ERROR_MESSAGE);
            jtvalor.requestFocus();
            return;
        }
        if(jralimento.isSelected() == false && jrpapelaria.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Selecione uma Categoria - Papelaria ou Alimentíceo", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
      
        try {
            String categoria = "";
            if(jralimento.isSelected()){
                categoria = "Alimentíceo";
            }
            else if(jrpapelaria.isSelected()){
                categoria = "Papelaria";
            }
            String nome = jtnome.getText();
            String descricao = jtdescricao.getText();
            String sabor = (String)cbsabor.getSelectedItem();
            String preco = jtvalor.getText();
            float valor;
            int nulo= 0;
            if(preco.contains(",")){
                 valor = Float.parseFloat(preco.replace(",", "."));
            }
            else{
                valor = Float.parseFloat(jtvalor.getText());
            }
            Produto novo = new Produto( nulo, nome, descricao, valor, categoria, sabor);
            novo.InserirBd();
            jtnome.requestFocus();
            jtdescricao.setText("");
            jtnome.setText("");
            cbsabor.setSelectedIndex(0);
            jtvalor.setText("");
            buttonGroup1.clearSelection();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Campo 'Valor' nao pode ser letra ou Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtvalor.requestFocus();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CadastrarSabor novo = new CadastrarSabor();
        novo.setLocation(jDesktopPane1.getWidth()/2 - novo.getWidth()/2, jDesktopPane1.getHeight()/2 - novo.getHeight()/2);
        Principal.jDesktopPane1.add(novo);
        novo.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbsaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsaborActionPerformed

    private void jralimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jralimentoActionPerformed
       cbsabor.setEnabled(true);
       jButton4.setEnabled(true);
    }//GEN-LAST:event_jralimentoActionPerformed

    private void jrpapelariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrpapelariaActionPerformed
       cbsabor.setEnabled(false);
       jButton4.setEnabled(false);
    }//GEN-LAST:event_jrpapelariaActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       Principal.verificarProduto = true;
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cbsabor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jldescricao;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlsabor;
    private javax.swing.JLabel jlvalor;
    private javax.swing.JRadioButton jralimento;
    private javax.swing.JRadioButton jrpapelaria;
    private javax.swing.JTextField jtdescricao;
    private javax.swing.JTextField jtnome;
    private javax.swing.JTextField jtvalor;
    // End of variables declaration//GEN-END:variables
}
