/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Cliente;
import Dados.Pedido;
import Dados.PedidoProduto;
import Dados.Produto;
import Dados.Usuario;
import static Interfaces.Principal.jDesktopPane1;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TabelaProdutosCadastrarPedido;
import util.TeclasPermitidas;

/**
 *
 * @author Aluno
 */
public class CadastrarPedido extends javax.swing.JInternalFrame {

    int codfinal;
    float valor_total = 0;
    float backup = 0;
    List<Produto> novo = new ArrayList<>();
    TabelaProdutosCadastrarPedido modelProduto = new TabelaProdutosCadastrarPedido();
    public static Usuario usuario;
    public static Cliente cliente;
    public static String clienteSelecionado;

    public CadastrarPedido(Usuario usuario) {

        initComponents();
        jTableprodutos.setModel(modelProduto);
        Inicializar();
        Principal.verificarPedido = false;
        this.usuario = usuario;

    }

    private void Inicializar() {
        jtCliente.setEditable(false);
        jtcod.setEnabled(false);
        jtvalorentrega.setEnabled(false);
        jtsinal.setEnabled(false);
        jf_data_sinal.setEnabled(false);
        jtdesconto.setDocument(new TeclasPermitidas());
        jtvalortotal.setEditable(false);
        jtfinal.setEditable(false);
        @SuppressWarnings("UnusedAssignment")
        ResultSet rs = null;
        @SuppressWarnings("UnusedAssignment")
        ResultSet rscod = null;
        Conexao nova = new Conexao();
        nova.getConexao();
        String sqlcodfinal = "SELECT codigo_pedido FROM dados.pedido";
        String aux = "";
        try {

            PreparedStatement smtBuscaCodFinal = nova.getConexao().prepareStatement(sqlcodfinal);

            rscod = smtBuscaCodFinal.executeQuery();

            while (rscod.next()) {
                aux = rscod.getString("codigo_pedido");
            }
            if (aux.equals("")) {
                aux = "0";
            }
            codfinal = Integer.parseInt(aux);
            codfinal++;
            aux = Integer.toString(codfinal);
            jtcod.setText(aux);

        } catch (SQLException ex) {
            Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs2 = null;
        String sql2 = "SELECT * from dados.produto order by nome;";
        try {

            PreparedStatement smtBuscaProduto = nova.getConexao().prepareStatement(sql2);
            rs2 = smtBuscaProduto.executeQuery();
            while (rs2.next()) {
                Produto dados = new Produto(rs2.getInt("codigo_produto"), rs2.getString("nome"), rs2.getString("descricao"), rs2.getFloat("valor"), rs2.getString("categoria"), rs2.getString("sabor"));
                novo.add(dados);
                cbproduto.addItem(rs2.getString("nome"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            nova.fecharConexao();
        }

    }

    public void LimparCampos() {

        jttema.setText("");
        jtnomecrianca.setText("");
        jtidadecrianca.setText("");
        jfentrega.setText("");
        jf_data_sinal.setText("");
        jtsinal.setText("");
        jtobs.setText("");
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(false);
        jtsinal.setText("");
        jtquantidade.setText("");
        jtvalortotal.setText("");
        jtfinal.setText("");
        jtdesconto.setText("");
        jtCliente.setText("");
        String aux;
        codfinal++;
        aux = Integer.toString(codfinal);
        jtcod.setText(aux);
        for (int i = 0; i < modelProduto.getRowCount(); i++) {
            modelProduto.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlidadecrianca = new javax.swing.JLabel();
        jtidadecrianca = new javax.swing.JTextField();
        jlentrega = new javax.swing.JLabel();
        jfentrega = new javax.swing.JFormattedTextField();
        jltema = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jttema = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jlcliente = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jlnomecrianca = new javax.swing.JLabel();
        jtnomecrianca = new javax.swing.JTextField();
        jlvalorentrega = new javax.swing.JLabel();
        jtvalorentrega = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtsinal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rbsinal1 = new javax.swing.JRadioButton();
        rbsinal2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jf_data_sinal = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jtobs = new javax.swing.JTextField();
        jtCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlproduto = new javax.swing.JLabel();
        cbproduto = new javax.swing.JComboBox<>();
        jlquantidade = new javax.swing.JLabel();
        jtquantidade = new javax.swing.JTextField();
        jbadicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableprodutos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtvalortotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtdesconto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfinal = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtcod = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastrar Pedido");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Gerais"));

        jlidadecrianca.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlidadecrianca.setText("Idade da Criança");

        jtidadecrianca.setToolTipText("Valor Numérico");

        jlentrega.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlentrega.setText("Data de Entrega:");

        try {
            jfentrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jfentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfentregaActionPerformed(evt);
            }
        });

        jltema.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jltema.setText("Tema:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Taxa de Entrega:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Sim");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jlcliente.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlcliente.setText("Cliente:");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Não");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jlnomecrianca.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlnomecrianca.setText("Nome da Criança:");

        jlvalorentrega.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlvalorentrega.setText("Valor:");

        jtvalorentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvalorentregaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Valor:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Sinal:");

        buttonGroup2.add(rbsinal1);
        rbsinal1.setText("Sim");
        rbsinal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsinal1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbsinal2);
        rbsinal2.setText("Não");
        rbsinal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsinal2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Data de Sinal:");

        try {
            jf_data_sinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Observações:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(rbsinal1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtsinal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbsinal2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jf_data_sinal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlentrega)
                            .addComponent(jlnomecrianca)
                            .addComponent(jlcliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtnomecrianca, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jtCliente))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlidadecrianca)
                            .addComponent(jltema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jttema)
                            .addComponent(jtidadecrianca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlvalorentrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtvalorentrega)))
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtobs, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtobs)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jltema)
                            .addComponent(jttema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcliente)
                            .addComponent(jLabel12)
                            .addComponent(jtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnomecrianca)
                            .addComponent(jtnomecrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlidadecrianca)
                            .addComponent(jtidadecrianca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlentrega)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jlvalorentrega)
                            .addComponent(jtvalorentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rbsinal1)
                            .addComponent(rbsinal2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtsinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jf_data_sinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados Produto"));

        jlproduto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlproduto.setText("Produto:");

        cbproduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--" }));

        jlquantidade.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlquantidade.setText("Quantidade:");

        jbadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar_produto.png"))); // NOI18N
        jbadicionar.setToolTipText("Adicionar Produto");
        jbadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbadicionarActionPerformed(evt);
            }
        });

        jTableprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableprodutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableprodutosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableprodutos);
        if (jTableprodutos.getColumnModel().getColumnCount() > 0) {
            jTableprodutos.getColumnModel().getColumn(0).setResizable(false);
            jTableprodutos.getColumnModel().getColumn(1).setResizable(false);
            jTableprodutos.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton4.setToolTipText("Excluir Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Sub Total:");

        jtvalortotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvalortotalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Descontos:");

        jtdesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdescontoActionPerformed(evt);
            }
        });
        jtdesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtdescontoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Valor Final:");

        jtfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfinalActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("(Indique o Valor e Pressione Enter)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jbadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbproduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlquantidade))
                                .addGap(108, 108, 108)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)
                                .addComponent(jtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jlproduto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlquantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbadicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlproduto)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Sair");
        jButton3.setToolTipText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.setToolTipText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cod:");

        jtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbadicionarActionPerformed
        Produto novoProduto = new Produto();
        float valor = 0;
        int quantidade;
        String quant;
        quant = jtquantidade.getText();
        quantidade = Integer.parseInt(quant);
        String produto = (String) cbproduto.getSelectedItem();
        Conexao nova = new Conexao();
        nova.getConexao();
        String selectValor = "SELECT * FROM dados.produto where nome = '" + produto + "'";
        ResultSet rs = null;
        try {
            PreparedStatement smtSelectValor = nova.getConexao().prepareStatement(selectValor);
            rs = smtSelectValor.executeQuery();
            while (rs.next()) {

                novoProduto.setNome(rs.getString("nome"));
                novoProduto.setQuantidade(quantidade);
                novoProduto.setValor(rs.getFloat("valor"));
                novoProduto.setValorFinal(novoProduto.getValor() * novoProduto.getQuantidade());
                valor = rs.getFloat("valor");
            }
            modelProduto.addRow(novoProduto);

            DecimalFormat decimal = new DecimalFormat("0.00");
            valor_total += valor * quantidade;
            jtvalortotal.setText(String.valueOf(decimal.format(valor_total)));
            jtfinal.setText(String.valueOf(decimal.format(valor_total)));
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            nova.fecharConexao();
        }


    }//GEN-LAST:event_jbadicionarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jtvalorentrega.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jtvalorentrega.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings({"UnnecessaryReturnStatement", "null"})
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jttema.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Tema nao pode ser Vazio", "ERROR", JOptionPane.ERROR_MESSAGE);
            jttema.requestFocus();
            return;
        }
        if (jtCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            @SuppressWarnings("MismatchedQueryAndUpdateOfCollection")
            ArrayList<String> produtoList = new ArrayList();
            @SuppressWarnings("MismatchedQueryAndUpdateOfCollection")
            ArrayList<String> quantidadeList = new ArrayList();
            String nome_crianca;
            String tema;
            int idade_crianca = 0;
            float valor_sinal = 0;
            float valor_entrega = 0;
            int codigo_cliente = 0;
            int produto = 0;
            nome_crianca = jtnomecrianca.getText();
            tema = jttema.getText();
            Calendar entrega = Calendar.getInstance();
            Calendar data_sinal = Calendar.getInstance();
            Calendar data_pedido = Calendar.getInstance();
            float desconto = 0;
            float valor_final;
            String obs = null;
            if (jtidadecrianca.getText().trim().equals("")) {

            } else {
                idade_crianca = Integer.parseInt(jtidadecrianca.getText());
            }
            if (jtsinal.getText().trim().equals("")) {

            } else {
                valor_sinal = Float.parseFloat(jtsinal.getText().replace(",", "."));
            }
            if (jtvalorentrega.getText().trim().equals("")) {

            } else {
                valor_entrega = Float.parseFloat(jtvalorentrega.getText().replace(",", "."));
            }
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            try {
                entrega.setTime(formato.parse(jfentrega.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (rbsinal1.isSelected()) {
                SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    data_sinal.setTime(fmt.parse(jf_data_sinal.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(CadastrarPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                data_sinal = null;
            }
            if (jtdesconto.getText().trim().equals("")) {

            } else {
                String auxiliar = jtdesconto.getText();
                if (auxiliar.contains(",")) {
                    desconto = Float.parseFloat(auxiliar.replace(",", "."));
                } else {
                    desconto = Float.parseFloat(auxiliar);

                }
            }
            if (jtobs.getText().trim().equals("")) {

            } else {
                obs = jtobs.getText();
            }
            codigo_cliente = cliente.getCodigo_cliente();
            valor_final = Float.parseFloat(jtfinal.getText().replace(",", "."));
            Pedido novo2 = new Pedido(codfinal, codigo_cliente, tema, valor_final, nome_crianca, idade_crianca, entrega, valor_sinal, valor_entrega, data_sinal, desconto, obs, "Aberto", usuario.getId_usuario(), data_pedido);
            novo2.InserirBd();

            int i;
            for (i = 0; i < 3; i++) {
                for (int j = 0; j < modelProduto.getRowCount(); j++) {
                    if (i == 0) {
                        produtoList.add(String.valueOf(modelProduto.getValueAt(j, i)));
                    } else if (i == 1) {
                        quantidadeList.add(String.valueOf(modelProduto.getValueAt(j, i)));
                    }
                }
            }

            PedidoProduto novoPedidoProduto = new PedidoProduto(produtoList, quantidadeList, codfinal);
            novoPedidoProduto.InserirBd();
            LimparCampos();
            Principal.tableModel.removeAllRow();
            Principal.tableModel.preencherJTable();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtvalorentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvalorentregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtvalorentregaActionPerformed

    private void jfentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfentregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfentregaActionPerformed

    private void jtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BuscarCliente novoBuscarCliente = new BuscarCliente("CadastrarPedido");
        jDesktopPane1.add(novoBuscarCliente);
        novoBuscarCliente.setLocation(jDesktopPane1.getWidth() / 2 - novoBuscarCliente.getWidth() / 2, jDesktopPane1.getHeight() / 2 - novoBuscarCliente.getHeight() / 2);
        novoBuscarCliente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTableprodutos.getSelectedRow() >= 0) {
            float apagar = (Float) jTableprodutos.getValueAt(jTableprodutos.getSelectedRow(), 2);
            int quantidade = (Integer) jTableprodutos.getValueAt(jTableprodutos.getSelectedRow(), 1);

            valor_total -= quantidade * apagar;
            DecimalFormat decimal = new DecimalFormat("0.00");
            jtvalortotal.setText(String.valueOf(decimal.format(valor_total)));
            jtfinal.setText(String.valueOf(decimal.format(valor_total)));
            modelProduto.removeRow(jTableprodutos.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para Excluir", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtvalortotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvalortotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtvalortotalActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Principal.verificarPedido = true;
    }//GEN-LAST:event_formInternalFrameClosed

    private void jtfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfinalActionPerformed

    private void jtdescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtdescontoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (usuario.getNivel() == 2) {
                JOptionPane.showMessageDialog(null, "Operação válida somente para Administrador", "Atenção", JOptionPane.INFORMATION_MESSAGE);

            } else {
                float desconto = 0, valorFinal = 0, valorTotal = 0;
                if (jtdesconto.getText().equals("")) {
                    valorFinal = Float.parseFloat(jtvalortotal.getText().replace(",", "."));
                    jtfinal.setText(String.valueOf(valorFinal).replace(",", "."));

                } else {
                    desconto = Float.parseFloat(jtdesconto.getText().replace(",", "."));
                    valorTotal = Float.parseFloat(jtvalortotal.getText().replace(",", "."));
                    valorFinal = valorTotal - desconto;
                    jtfinal.setText(String.valueOf(valorFinal));
                }

            }

        }
    }//GEN-LAST:event_jtdescontoKeyPressed

    private void jtdescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdescontoActionPerformed
    }//GEN-LAST:event_jtdescontoActionPerformed

    private void jTableprodutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableprodutosKeyPressed

    }//GEN-LAST:event_jTableprodutosKeyPressed

    private void rbsinal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsinal1ActionPerformed
        if (rbsinal1.isSelected()) {
            jtsinal.setEnabled(true);
            jf_data_sinal.setEnabled(true);
        }
    }//GEN-LAST:event_rbsinal1ActionPerformed

    private void rbsinal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsinal2ActionPerformed
        if (rbsinal2.isSelected()) {
            jtsinal.setEnabled(false);
            jf_data_sinal.setEnabled(false);
        }
    }//GEN-LAST:event_rbsinal2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String tela = "Cadastrar Pedido";
        BuscarProduto novoBuscarProduto = new BuscarProduto(tela);
        jDesktopPane1.add(novoBuscarProduto);
        novoBuscarProduto.setLocation(jDesktopPane1.getWidth() / 2 - novoBuscarProduto.getWidth() / 2, jDesktopPane1.getHeight() / 2 - novoBuscarProduto.getHeight() / 2);
        novoBuscarProduto.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> cbproduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableprodutos;
    private javax.swing.JButton jbadicionar;
    private javax.swing.JFormattedTextField jf_data_sinal;
    private javax.swing.JFormattedTextField jfentrega;
    private javax.swing.JLabel jlcliente;
    private javax.swing.JLabel jlentrega;
    private javax.swing.JLabel jlidadecrianca;
    private javax.swing.JLabel jlnomecrianca;
    private javax.swing.JLabel jlproduto;
    private javax.swing.JLabel jlquantidade;
    private javax.swing.JLabel jltema;
    private javax.swing.JLabel jlvalorentrega;
    public static javax.swing.JTextField jtCliente;
    private javax.swing.JTextField jtcod;
    private javax.swing.JTextField jtdesconto;
    private javax.swing.JTextField jtfinal;
    private javax.swing.JTextField jtidadecrianca;
    private javax.swing.JTextField jtnomecrianca;
    private javax.swing.JTextField jtobs;
    private javax.swing.JTextField jtquantidade;
    private javax.swing.JTextField jtsinal;
    private javax.swing.JTextField jttema;
    private javax.swing.JTextField jtvalorentrega;
    private javax.swing.JTextField jtvalortotal;
    private javax.swing.JRadioButton rbsinal1;
    private javax.swing.JRadioButton rbsinal2;
    // End of variables declaration//GEN-END:variables
}
