/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Pedido;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.parse_action;
import javax.swing.JOptionPane;
import model.TabelaPedidoRelatorio;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author joao
 */
public class Relatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relatorio
     */
    TabelaPedidoRelatorio tableModel = new TabelaPedidoRelatorio();
    public Relatorio() {
        
        initComponents();
        jTable1.setModel(tableModel);
        jtDescontos.setEditable(false);
        jtValorFinal.setEditable(false);
        jtValorTotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDataDe = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDataAte = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jrAberto = new javax.swing.JRadioButton();
        jrFechado = new javax.swing.JRadioButton();
        jrAmbos = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtValorTotal = new javax.swing.JTextField();
        jtDescontos = new javax.swing.JTextField();
        jtValorFinal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtSinais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selecione o Tipo de Pedido"));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("De:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Até:");

        jButton1.setBackground(new java.awt.Color(58, 65, 84));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Gerar Relatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrAberto);
        jrAberto.setText("Abertos");

        buttonGroup1.add(jrFechado);
        jrFechado.setText("Fechados");

        buttonGroup1.add(jrAmbos);
        jrAmbos.setText("Ambos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jrAberto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrFechado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrAmbos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAberto)
                    .addComponent(jrFechado)
                    .addComponent(jrAmbos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Relatório"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Valor Total:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Descontos:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Valor Final:");

        jtValorTotal.setBackground(new java.awt.Color(0, 204, 204));
        jtValorTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jtDescontos.setBackground(new java.awt.Color(255, 0, 0));
        jtDescontos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jtValorFinal.setBackground(new java.awt.Color(0, 204, 0));
        jtValorFinal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jButton2.setBackground(new java.awt.Color(58, 65, 84));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Gerar PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Sinais:");

        jtSinais.setBackground(new java.awt.Color(0, 102, 102));
        jtSinais.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Somente em pedidos Abertos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(jtDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtSinais, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtSinais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jrAberto.isSelected() || jrAmbos.isSelected() || jrFechado.isSelected()){
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Status do Pedido", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        tableModel.removeAllRow();
        jtDescontos.setText("");
        jtValorFinal.setText("");
        jtValorTotal.setText("");
        Date dataDe, dataAte, dataEntrega, dataPedido;
        DecimalFormat formato = new DecimalFormat("0.00");
        String nomeCliente = "";
        String nomeVendedor = "";
        String buscarPedidos = "";
        float valorTotal = 0, valorFinal = 0, descontos = 0, sinais = 0;
        if(jrAmbos.isSelected()){
            buscarPedidos = "SELECT pedido.codigo_pedido, cliente.nome, pedido.codigo_cliente, pedido.codigo_usuario , pedido.tema, pedido.data_pedido, pedido.data_entrega, pedido.valor_sinal, pedido.desconto, pedido.valor_total, pedido.status, usuario.usuario FROM dados.pedido, dados.cliente, dados.usuario where pedido.data_entrega between ? and ? and pedido.codigo_cliente = cliente.codigo_cliente and pedido.codigo_usuario = usuario.id_usuario order by pedido.data_pedido asc";
        }else if(jrAberto.isSelected()){
            buscarPedidos = "SELECT pedido.codigo_pedido, cliente.nome, pedido.codigo_cliente, pedido.codigo_usuario , pedido.tema, pedido.data_pedido, pedido.data_entrega, pedido.valor_sinal, pedido.desconto, pedido.valor_total, pedido.status, usuario.usuario FROM dados.pedido, dados.cliente, dados.usuario where pedido.data_entrega between ? and ? and pedido.codigo_cliente = cliente.codigo_cliente  and pedido.codigo_usuario = usuario.id_usuario  and pedido.status = 'Aberto'  order by pedido.data_pedido asc";
        }else if(jrFechado.isSelected()){
            buscarPedidos = "SELECT pedido.codigo_pedido, cliente.nome, pedido.codigo_cliente, pedido.codigo_usuario , pedido.tema, pedido.data_pedido, pedido.data_entrega, pedido.valor_sinal, pedido.desconto, pedido.valor_total, pedido.status, usuario.usuario FROM dados.pedido, dados.cliente, dados.usuario where pedido.data_entrega between ? and ? and pedido.codigo_cliente = cliente.codigo_cliente  and pedido.codigo_usuario = usuario.id_usuario  and pedido.status = 'Fechado'  order by pedido.data_pedido asc";
        }   
        Conexao minhaConexao = new Conexao();
        ResultSet rsPedidos = null;
        dataDe = jDataDe.getDate();
        dataAte = jDataAte.getDate();
        if(dataDe == null){
            JOptionPane.showMessageDialog(null, "Selecione uma Data Primária", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
                    
        }
        if(dataAte == null){
            JOptionPane.showMessageDialog(null, "Selecione uma Data Secundária", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
                    
        }
        try {
            PreparedStatement stmBuscarPedido = minhaConexao.getConexao().prepareStatement(buscarPedidos);
            stmBuscarPedido.setDate(1, new java.sql.Date(dataDe.getTime()));
            stmBuscarPedido.setDate(2, new java.sql.Date(dataAte.getTime()));
            rsPedidos = stmBuscarPedido.executeQuery();
            if(rsPedidos.next()){
                do{
                   Pedido novo =  new Pedido();
                 Calendar convertido = Calendar.getInstance();
                 Calendar convertidoDataPedido = Calendar.getInstance();
                
                dataPedido = rsPedidos.getDate("data_pedido");
                dataEntrega = rsPedidos.getDate("data_entrega");
                convertidoDataPedido.setTime(dataPedido);
                convertido.setTimeInMillis(dataEntrega.getTime());
                novo.setData_entrega(convertido);
                novo.setData_pedido(convertidoDataPedido);
                novo.setCodigo_pedido(rsPedidos.getInt("codigo_pedido"));
                novo.setCodigo_cliente(rsPedidos.getInt("codigo_cliente"));
                novo.setDesconto(rsPedidos.getFloat("desconto"));
                
                novo.setTema(rsPedidos.getString("tema"));
                novo.setValor_sinal(rsPedidos.getFloat("valor_sinal"));
                novo.setValor_total(rsPedidos.getFloat("valor_total"));
                novo.setStatus(rsPedidos.getString("status"));  
                novo.setCodigo_usuario(rsPedidos.getInt("codigo_usuario"));
                nomeCliente = rsPedidos.getString("nome");
                nomeVendedor = rsPedidos.getString("usuario");
                valorTotal = valorTotal + (novo.getValor_total() + novo.getDesconto());
                descontos = descontos + novo.getDesconto();
                if(jrAberto.isSelected() || jrAmbos.isSelected()){
                    if(novo.getStatus().equals("Aberto")){
                        sinais = sinais + novo.getValor_sinal();
                    }

                        
                }
                tableModel.addRow(novo, nomeCliente, nomeVendedor);
                
                    
                }while(rsPedidos.next());
                valorFinal = valorTotal - descontos;
                jtValorTotal.setText(String.valueOf(formato.format(valorTotal)));
                jtDescontos.setText(String.valueOf(formato.format(descontos)));
                jtValorFinal.setText(String.valueOf(formato.format(valorFinal)));
                if(jrAberto.isSelected() || jrAmbos.isSelected()){
                    jtSinais.setText(String.valueOf(sinais));
                }
            }else{
                JOptionPane.showMessageDialog(null, "Nao foi Encontrado Pedido no Período Especificado", "Atenção", JOptionPane.INFORMATION_MESSAGE );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            minhaConexao.fecharConexao();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jrAmbos.isSelected()){
            JOptionPane.showMessageDialog(null, "Relátorio de Ambos os pedidos ainda em Desenvolvimento, Em Breve Disponível ;)", "Logo Logo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Date dataDe = jDataDe.getDate();
        Date dataAte = jDataAte.getDate();
        String status = "";
        if(jrAberto.isSelected()){
            status  = "Aberto";
        }else if(jrFechado.isSelected()){
            status = "Fecahdo";
        }
        
        if(dataDe == null){
            JOptionPane.showMessageDialog(null, "Selecione uma Data Primária", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
                    
        }
        if(dataAte == null){
            JOptionPane.showMessageDialog(null, "Selecione uma Data Secundária", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
                    
        }
        int contador = tableModel.getRowCount();
        if(contador == 0){

            JOptionPane.showMessageDialog(null, "Por Favor! Clique no botão Gerar Relatorio para saber a disponibilidade de pedidos para esse intervalo de datas" + "\n" + "Apos Confirmado volte e Gere o PDF.", "Atenção", JOptionPane.WARNING_MESSAGE);
          
            return;
        }
        float valorTotal = Float.parseFloat(jtValorTotal.getText().replace(",", "."));
        Conexao minhaConexao = new Conexao();
        Map parametros = new HashMap();
        InputStream imagem = getClass().getResourceAsStream("/Relatorios/logo.jpg");
        parametros.put("dataDe", dataDe);
        parametros.put("dataAte", dataAte);
        parametros.put("valortotal", valorTotal);
        parametros.put("imagelogo", imagem);
        parametros.put("status", status);
        InputStream local = getClass().getResourceAsStream("/Relatorios/relatoriovendas.jasper");
        
        try {
            JasperPrint print = JasperFillManager.fillReport( local, parametros, minhaConexao.getConexao() );
            JasperViewer jasperView = new JasperViewer(print, false);
            jasperView.setVisible(true);
            jasperView.toFront();
            
        } catch (JRException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            minhaConexao.fecharConexao();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDataAte;
    private com.toedter.calendar.JDateChooser jDataDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrAberto;
    private javax.swing.JRadioButton jrAmbos;
    private javax.swing.JRadioButton jrFechado;
    private javax.swing.JTextField jtDescontos;
    private javax.swing.JTextField jtSinais;
    private javax.swing.JTextField jtValorFinal;
    private javax.swing.JTextField jtValorTotal;
    // End of variables declaration//GEN-END:variables
}
