/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import Dados.Usuario;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class TelaLoginFinal extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginFinal
     */
    
    public TelaLoginFinal() {
        initComponents();
        CanvasTelaLogin canvas = new CanvasTelaLogin();
        this.painelLogo.add(canvas);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JPasswordField();
        painelLogo = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(58, 65, 84));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(217, 81, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sair");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-icon.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/padlock.png"))); // NOI18N

        jtSenha.setForeground(new java.awt.Color(102, 102, 102));
        jtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSenhaKeyPressed(evt);
            }
        });

        painelLogo.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton3.setText("Criar novo Usuário");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String senhaDigitada = String.valueOf(jtSenha.getPassword());
        if(jtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Usuario não pode ser em Branco", "Atenção'", JOptionPane.INFORMATION_MESSAGE);
            jtUsuario.requestFocus();
            return;
        }
        if(senhaDigitada.equals("")){
            JOptionPane.showMessageDialog(null, "Campo Senha não pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtSenha.requestFocus();
            return;
        }
        
        String sqlBuscarUsuario = "SELECT usuario, id_usuario, senha, nivel, nome FROM dados.usuario where usuario = ? ";
        Conexao minhaConexao = new Conexao();
        ResultSet rsUsuario = null;
        minhaConexao.getConexao();
        try {
            PreparedStatement stmBuscarUsuario = minhaConexao.getConexao().prepareStatement(sqlBuscarUsuario);
            stmBuscarUsuario.setString(1, jtUsuario.getText());
            rsUsuario = stmBuscarUsuario.executeQuery(); 
            if(rsUsuario.next()){
                String senha = rsUsuario.getString("senha");
                if(senhaDigitada.equals(senha)){
                    Usuario novo = new Usuario();
                    novo.setNivel(rsUsuario.getInt("nivel"));
                    novo.setNome(rsUsuario.getString("nome"));
                    novo.setSenha(rsUsuario.getString("senha"));
                    novo.setUsuario(rsUsuario.getString("usuario"));
                    novo.setId_usuario(rsUsuario.getInt("id_usuario"));
                    Principal nova = new Principal(novo);
                    nova.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Senha Incorreta", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    jtSenha.requestFocus();
                    return;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Usuário Inexistente", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                jtUsuario.requestFocus();
                return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaLoginFinal.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            minhaConexao.fecharConexao();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       TelaCadastro telaCadastro = new TelaCadastro();
       telaCadastro.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSenhaKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           String senhaDigitada = String.valueOf(jtSenha.getPassword());
        if(jtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Usuario não pode ser em Branco", "Atenção'", JOptionPane.INFORMATION_MESSAGE);
            jtUsuario.requestFocus();
            return;
        }
        if(senhaDigitada.equals("")){
            JOptionPane.showMessageDialog(null, "Campo Senha não pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtSenha.requestFocus();
            return;
        }
        
        String sqlBuscarUsuario = "SELECT usuario, id_usuario, senha, nivel, nome FROM dados.usuario where usuario = ? ";
        Conexao minhaConexao = new Conexao();
        ResultSet rsUsuario = null;
        minhaConexao.getConexao();
        try {
            PreparedStatement stmBuscarUsuario = minhaConexao.getConexao().prepareStatement(sqlBuscarUsuario);
            stmBuscarUsuario.setString(1, jtUsuario.getText());
            rsUsuario = stmBuscarUsuario.executeQuery(); 
            if(rsUsuario.next()){
                String senha = rsUsuario.getString("senha");
                if(senhaDigitada.equals(senha)){
                    Usuario novo = new Usuario();
                    novo.setNivel(rsUsuario.getInt("nivel"));
                    novo.setNome(rsUsuario.getString("nome"));
                    novo.setSenha(rsUsuario.getString("senha"));
                    novo.setUsuario(rsUsuario.getString("usuario"));
                    novo.setId_usuario(rsUsuario.getInt("id_usuario"));
                    Principal nova = new Principal(novo);
                    nova.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Senha Incorreta", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    jtSenha.requestFocus();
                    return;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Usuário Inexistente", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                jtUsuario.requestFocus();
                return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaLoginFinal.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            minhaConexao.fecharConexao();
        }
           
       }
    }//GEN-LAST:event_jtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JPanel painelLogo;
    // End of variables declaration//GEN-END:variables
}
