/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        CanvasTelaCadastro canvas = new CanvasTelaCadastro();
        jPanelCadastro.add(canvas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtUsuario = new javax.swing.JTextField();
        jtSenha = new javax.swing.JPasswordField();
        jtSenhaAgain = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(392, 440));

        jPanelCadastro.setMinimumSize(new java.awt.Dimension(392, 115));
        jPanelCadastro.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("Nome de Usuário:");

        jLabel3.setText("Senha:");

        jLabel4.setText("Repita Senha:");

        jtNome.setForeground(new java.awt.Color(102, 102, 102));

        jtUsuario.setForeground(new java.awt.Color(102, 102, 102));

        jtSenha.setForeground(new java.awt.Color(102, 102, 102));

        jtSenhaAgain.setForeground(new java.awt.Color(102, 102, 102));

        jButton1.setBackground(new java.awt.Color(46, 139, 87));
        jButton1.setText("Cadastrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtSenhaAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtSenhaAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String senha = String.valueOf(jtSenha.getPassword());
        String senhaConfirma = String.valueOf(jtSenhaAgain.getPassword());
        
        if(jtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Nome não pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtNome.requestFocus();
            return;
        }
        if(jtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Usuario nao pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtUsuario.requestFocus();
            return;
        }
        Conexao minhaConexao = new Conexao();
        String sqlBuscarUsuarios = "SELECT usuario FROM dados.usuario WHERE usuario = ?;";
        ResultSet rsNomeUsuario = null;
        try {
            PreparedStatement stmBuscarNomeUsuario = minhaConexao.getConexao().prepareStatement(sqlBuscarUsuarios);
            stmBuscarNomeUsuario.setString(1, jtUsuario.getText());
            rsNomeUsuario = stmBuscarNomeUsuario.executeQuery();
            if(rsNomeUsuario.next()){
                JOptionPane.showMessageDialog(null, "Usuário já Existente", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                jtUsuario.requestFocus();
                return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
           
        }
        if(senha.equals("")){
            JOptionPane.showMessageDialog(null, "Campo Senha não pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtSenha.requestFocus();
            return;
        }
        if(senhaConfirma.equals("")){
            JOptionPane.showMessageDialog(null, "Campor Senha não pode ser em Branco", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtSenhaAgain.requestFocus();
            return;
        }
        if(senha.equals(senhaConfirma)){
            
        }else{
            JOptionPane.showMessageDialog(null, "Senhas não correspondem", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            jtSenhaAgain.requestFocus();
            return;
        }
        String sqlBuscarUsuario = "SELECT usuario FROM dados.usuario where usuario = '?'";
        String sqlInsereUsuario = "INSERT INTO dados.usuario(usuario, senha, nivel, nome) VALUES (?, ?, ?, ?);";
        ResultSet rsConferirUsuario = null;
        try {
            minhaConexao.getConexao();
            PreparedStatement stmBuscarUsuario = minhaConexao.getConexao().prepareStatement(sqlBuscarUsuario);
            rsConferirUsuario = stmBuscarUsuario.executeQuery();
            if(rsConferirUsuario.next()){
                JOptionPane.showMessageDialog(null, "Usuario já Existente", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                jtUsuario.requestFocus();
                return;
                        
            }
            
            PreparedStatement stmInsereUsuario = minhaConexao.getConexao().prepareStatement(sqlInsereUsuario);
            stmInsereUsuario.setString(1, jtUsuario.getText());
            stmInsereUsuario.setString(2, senha);
            stmInsereUsuario.setInt(3, 2);
            stmInsereUsuario.setString(4, jtNome.getText());
            stmInsereUsuario.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            jtNome.setText("");
            jtSenha.setText("");
            jtSenhaAgain.setText("");
            jtUsuario.setText("");
            jtNome.requestFocus();
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            minhaConexao.fecharConexao();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JTextField jtNome;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JPasswordField jtSenhaAgain;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
